jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List Directory
        run: ls -R  # Optional: This helps you verify the directory structure

      - name: Build with Maven
        run: |
          cd git_batchdemo  # Navigate to the directory containing pom.xml
          mvn clean package


